spring.application.name=Rigel
origin=http://localhost:5173
# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/rigel_db
spring.jpa.properties.hibernate.default_schema=rigel
spring.datasource.username=rigel_root
#TODO: Change the password to a secure one before deploying to production
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.open-in-view=false
# Server Configuration
server.port=8080
spring.thymeleaf.check-template-location=false
# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=beltranrojoporfirio@gmail.com
spring.mail.password=hycoluuzbxofmklt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.base-url=${origin}
app.mail.from=beltranrojoporfirio@gmail.com
app.mail.token-expiration-hours=48
# JWT Configuration
jwt.secret=mySuperSecretKeyThatIsAtLeast32CharactersLong123!
jwt.expiration=3600000
jwt.refresh=86400000
# Logging
logging.pattern.level=%5p [corr:%X{correlationId:-N/A}]
logging.level.com.korebit.rigel.interceptor.LogInterceptor=DEBUG
# Cloudinary Configuration (optional)
cloudinary.api-key=611898533685231
cloudinary.api-secret=4FLlFyrf-ya_GaS5dIsCJYp3LG8
cloudinary.cloud-name=dkcekderd
cloudinary.folder=rigel/products
# Image Storage Configuration
image.storage.local-path=./uploads
